spring.application.name=payguard

spring.datasource.url=jdbc:mysql://localhost:3306/payguard
spring.datasource.username=payguard_user
spring.datasource.password=${PAYGUARD_DB_PASSWORD}

# Veritabanı şemasını Flyway yönetir.
# Hibernate yalnızca entity ve tablo yapılarının uyumlu olduğunu kontrol eder.
spring.jpa.hibernate.ddl-auto=validate

# Controller dışında lazy relation kullanılmasını engeller.
spring.jpa.open-in-view=false