spring.application.name=payguard

# Veritabanı şemasını Flyway yönetir.
# Hibernate yalnızca entity ve tablo yapılarının uyumunu kontrol eder.
spring.jpa.hibernate.ddl-auto=validate

# Controller dışında lazy relation kullanılmasını engeller.
spring.jpa.open-in-view=false